#!/usr/bin/env bash

if [[ $# -lt 1 ]]; then
  echo
  echo "USAGE: ./get-zone [COMMAND]"
  echo
  echo "Commands:"
  echo "  setup - Setup the necessary Docker container."
  echo
  echo "  run <namecheap_username> <namecheap_password> <domain> - Run the script to get your NameCheap DNS Zone File."
  echo
  echo "  bash - Run bash in the container environment."
  echo
  echo "######################################################################"
  echo "NOTE: This script requires that you have Docker installed."
  echo "######################################################################"
  echo
  exit
fi

while [[ $# -gt 0 ]]; do
  param="$1" 
  case "$param" in
    setup)
    echo "Building get-namecheap-zone-file Docker container..."
    docker build . -t get-namecheap-zone-file
    ;;

    run)
    shift
    docker run -it --rm -v $(pwd):/app:cached --shm-size=2g get-namecheap-zone-file ./wrapper.sh $@
    break
    ;;

    bash)
    docker run -it --rm -v $(pwd):/app:cached --shm-size=2g get-namecheap-zone-file bash
    break
    ;;

    *)
    echo "Unknown command: $param"
    break
    ;;
  esac
  shift
done

